import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { cookies } from "next/headers";
import { ShoppingBagIcon } from "lucide-react";
import { ActiveLink } from "@/components/atoms/ActiveLink";
import "./globals.css";
import { executeQuery } from "@/api/products";
import { CartGetByIdDocument } from "@/gql/graphql";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const cartId = cookies().get("cartId")?.value;
	const cart = cartId
		? await executeQuery({ query: CartGetByIdDocument, variables: { id: cartId }, next: { tags: ["cart"] } })
		: null;
	const count = cart?.order?.orderItems.length || 0;
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="container">
					<nav className="flex flex-row items-center justify-between">
						<ul className="mt-4 flex items-center justify-center space-x-4">
							<li>
								<ActiveLink href="/">Home</ActiveLink>
							</li>
							<li>
								<ActiveLink href="/products">Products</ActiveLink>
							</li>
						</ul>
						<span className="flex flex-row items-center">
							<Link href={"/cart"}>
								<ShoppingBagIcon />
							</Link>
							{<span className="ml-2">{count}</span>}
						</span>
					</nav>
					<main className="h-screen bg-white">
						<section className="mx-auto max-w-md p-12 sm:max-w-2xl sm:py-16 md:max-w-4xl lg:max-w-7xl">
							{children}
						</section>
					</main>
				</div>
			</body>
		</html>
	);
}
